import { Brief, type TecnicaId } from "@/lib/contratos";
import { COMPLETAR } from "@/componentes/dinero";
import type { EntradaVitrina, FilaFicha } from "@/lib/vitrina/tipos";

// Los 8 briefs de la vitrina (docs/bitacora/plan-v2.md). Colombia, pago contraentrega.
//
// Fidelidad:
// - Precio y garantía los define el vendedor (sin «precio anterior»: un tachado sin respaldo es una promesa que no se puede verificar) (aquí, valores realistas del mercado colombiano);
//   el precio que traiga SerpAPI es solo referencia y nunca se copia.
// - Sin testimonios, calificaciones ni número de opiniones: la prueba social queda vacía.
// - Los beneficios no llevan cifras. Las medidas y especificaciones que el vendedor no dio van como [COMPLETAR].

const brief = (b: unknown): Brief => Brief.parse(b);

/** Ocho técnicas menos la 2 (sustractivo): la vitrina pide de 12 a 16 secciones y esa técnica las recortaría a 7. */
const TECNICAS: TecnicaId[] = ["semilla", "ambicioso", "critico", "imagenes", "video", "negativas", "humana"];

const F = (nombre: string, valor: string = COMPLETAR, unidad?: string): FilaFicha => ({ nombre, valor, ...(unidad ? { unidad } : {}) });

export const VITRINA: readonly EntradaVitrina[] = [
  // ---------- Espaciales ----------
  {
    numero: 1,
    slug: "proyector-galaxias-auroras",
    tematica: "espacio",
    tecnicas: TECNICAS,
    numeroSemilla: 214,
    bancos: ["b1", "b5", "p-hogar"],
    claves: ["galaxia", "nebulosa", "aurora", "cielo", "noche", "estrellas", "galaxy", "nebula", "aurora", "night", "stars", "milky way", "proyector", "projector", "luz de noche", "night light", "planetarium"],
    temasCuriosos: ["b1", "b5"],
    widget: { variante: "auroras", titulo: "Las auroras, ahora mismo", contexto: "Tu techo puede tener esas mismas luces, sin viajar al polo." },
    fuentes: ["nasa-images", "noaa-kp", "serpapi"],
    consultas: { shopping: "proyector de galaxias y auroras", preguntas: "proyector de galaxias aurora vale la pena" },
    tituloFicha: "Ficha técnica",
    ficha: [F("Tipo", "Proyector de galaxias y auroras"), F("Uso", "Interiores: cuarto o sala"), F("Alimentación"), F("Peso", COMPLETAR, "g")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Proyector de galaxias y auroras",
      categoria: "hogar",
      problema: "Tu cuarto de noche es un techo oscuro con una luz blanca que despierta más de lo que relaja.",
      publico: "Jóvenes y familias que quieren un ambiente tranquilo para dormir, leer o ver series en casa.",
      beneficios: [
        "Llena el techo con nubes de galaxia y luces de aurora",
        "Se enciende y se apaga sin instalar nada",
        "Colores y movimiento para cada momento de la noche",
        "Cabe en una mesa de noche y no estorba",
      ],
      precio: { valor: 89900, moneda: "COP" },
      objeciones: [
        "¿Se ve bien con la luz encendida?",
        "¿Sirve como luz de noche para niños?",
        "¿Necesito instalarlo?",
        "¿Cuánto tarda en llegar?",
        "¿Qué pasa si llega dañado?",
      ],
      nivelConciencia: "solucion",
      incluye: ["Proyector de galaxias y auroras", "Cable de carga", "Manual en español"],
      garantia: { dias: 30, condiciones: "Si llega con un defecto de fábrica, lo cambiamos sin costo." },
      coloresMarca: ["#5eead4", "#050816"],
      intensidad: 3,
    }),
  },
  {
    numero: 2,
    slug: "lampara-luna-3d",
    tematica: "espacio",
    tecnicas: TECNICAS,
    numeroSemilla: 371,
    bancos: ["b3", "b1", "p-hogar"],
    claves: ["luna", "lunar", "crater", "noche", "moon", "lunar", "crater", "earthrise", "night", "lampara", "lamp", "esfera", "sphere", "globe", "luz de noche", "night light"],
    temasCuriosos: ["b3"],
    widget: { variante: "fase-lunar", titulo: "La Luna de hoy", contexto: "Una lámpara que reproduce la misma Luna que ves por la ventana." },
    fuentes: ["nasa-images", "usno-luna", "serpapi"],
    consultas: { shopping: "lámpara de luna 3D", preguntas: "lámpara de luna 3d cómo funciona" },
    tituloFicha: "Ficha técnica",
    ficha: [F("Tipo", "Lámpara de luna 3D"), F("Uso", "Escritorio, repisa o mesa de noche"), F("Diámetro", COMPLETAR, "cm"), F("Alimentación")],
    textoCta: "Pídela y paga al recibir",
    brief: brief({
      nombre: "Lámpara de luna 3D",
      categoria: "hogar",
      problema: "La luz de noche de siempre es plana y fría, y no da ganas de quedarse a mirarla.",
      publico: "Personas que quieren decorar su cuarto o regalar algo distinto, y familias con niños que le tienen miedo a la oscuridad.",
      beneficios: [
        "Reproduce el relieve de la Luna, cráter por cráter",
        "Da una luz cálida y suave para dormir o leer",
        "Cambia de tono con un toque",
        "Se ve bien en un escritorio, una repisa o la mesa de noche",
      ],
      precio: { valor: 59900, moneda: "COP" },
      objeciones: [
        "¿Alumbra lo suficiente para leer?",
        "¿Es frágil?",
        "¿Sirve de regalo?",
        "¿Cuánto tarda en llegar?",
        "¿Qué pasa si llega dañada?",
      ],
      nivelConciencia: "solucion",
      incluye: ["Lámpara de luna 3D con su base", "Cable de carga"],
      garantia: { dias: 30, condiciones: "Si llega con un defecto de fábrica, la cambiamos sin costo." },
      coloresMarca: ["#f5d67a", "#0a0d1a"],
      intensidad: 3,
    }),
  },
  {
    numero: 3,
    slug: "telescopio-principiantes",
    tematica: "espacio",
    tecnicas: TECNICAS,
    numeroSemilla: 502,
    bancos: ["b4", "b3", "b1", "p-tecnologia"],
    claves: ["planeta", "saturno", "jupiter", "marte", "luna", "telescopio", "planet", "saturn", "jupiter", "mars", "moon", "telescope", "tripod", "astronomer", "astronomo"],
    temasCuriosos: ["b4", "b1"],
    widget: { variante: "asteroides", titulo: "Hoy en el cielo", contexto: "Con un telescopio, el cielo de tu casa cambia cada noche." },
    fuentes: ["nasa-images", "neows", "serpapi"],
    consultas: { shopping: "telescopio para principiantes", preguntas: "telescopio para principiantes qué debo saber" },
    tituloFicha: "Ficha técnica",
    ficha: [F("Tipo", "Telescopio para principiantes"), F("Diámetro de apertura", COMPLETAR, "mm"), F("Distancia focal", COMPLETAR, "mm")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Telescopio para principiantes",
      categoria: "otro",
      problema: "Quieres ver la Luna y los planetas, pero los telescopios que encuentras son caros y difíciles de armar.",
      publico: "Curiosos del cielo, familias y estudiantes que quieren empezar a observar sin gastar de más.",
      beneficios: [
        "Se arma en pocos minutos y sin herramientas",
        "Muestra los cráteres de la Luna con claridad",
        "Trae lo necesario para la primera noche de observación",
        "Liviano para llevarlo al patio o a la terraza",
      ],
      precio: { valor: 189900, moneda: "COP" },
      objeciones: [
        "¿Se alcanzan a ver los anillos de Saturno?",
        "¿Sirve para un niño?",
        "¿Es difícil de armar?",
        "¿Se puede usar desde la ciudad?",
        "¿Qué pasa si llega dañado?",
      ],
      nivelConciencia: "solucion",
      incluye: ["Telescopio con su trípode", "Oculares", "Manual en español"],
      garantia: { dias: 30, condiciones: "Si llega con un defecto de fábrica, lo cambiamos sin costo." },
      coloresMarca: ["#ffb454", "#0b1020"],
      intensidad: 3,
    }),
  },
  {
    numero: 4,
    slug: "kit-cohete-educativo",
    tematica: "espacio",
    tecnicas: TECNICAS,
    numeroSemilla: 618,
    bancos: ["b7", "b1", "p-hogar"],
    claves: ["cohete", "lanzamiento", "estacion", "astronauta", "rocket", "launch", "space station", "astronaut", "juguete", "toy", "model", "ninos", "children", "kids"],
    temasCuriosos: ["b7", "b5", "b1"],
    widget: { variante: "cuenta-regresiva-lanzamiento", titulo: "El próximo despegue", contexto: "Que tus hijos vean el conteo real y armen su propio cohete." },
    fuentes: ["nasa-images", "lanzamientos", "serpapi"],
    consultas: { shopping: "kit de cohete educativo niños", preguntas: "kit de cohete educativo para niños desde qué edad" },
    tituloFicha: "Ficha técnica",
    ficha: [F("Tipo", "Kit de cohete educativo"), F("Uso", "Con supervisión de un adulto"), F("Edad recomendada", COMPLETAR, "años")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Kit de cohete educativo para niños",
      categoria: "otro",
      problema: "Tus hijos pasan horas frente a una pantalla y buscas un plan que les enseñe algo de verdad.",
      publico: "Madres, padres y profesores de niños en edad escolar que quieren un plan de ciencia para hacer en familia.",
      beneficios: [
        "Arman su propio cohete y aprenden cómo despega",
        "Un plan para hacer en familia, al aire libre",
        "Cada paso se explica con instrucciones claras para niños",
        "Mezcla juego y ciencia lejos de las pantallas",
      ],
      precio: { valor: 79900, moneda: "COP" },
      objeciones: [
        "¿Necesita un adulto para usarlo?",
        "¿Desde qué edad se puede usar?",
        "¿Se necesita algo más para lanzarlo?",
        "¿Sirve para un salón de clase?",
        "¿Qué pasa si llega incompleto?",
      ],
      nivelConciencia: "solucion",
      incluye: ["Piezas del cohete", "Guía de armado en español"],
      garantia: { dias: 30, condiciones: "Si llega incompleto o con un defecto de fábrica, lo cambiamos sin costo." },
      coloresMarca: ["#ff7a59", "#070b18"],
      intensidad: 3,
    }),
  },
  // ---------- De producto ----------
  {
    numero: 5,
    slug: "colageno-hidrolizado-vitrina",
    tematica: "producto",
    tecnicas: TECNICAS,
    numeroSemilla: 145,
    bancos: ["p-bienestar", "p-belleza"],
    claves: ["colageno", "polvo", "suplemento", "bienestar", "vaso", "collagen", "powder", "supplement", "healthy", "drink", "glass"],
    fuentes: ["open-food-facts", "serpapi"],
    consultas: { shopping: "colágeno hidrolizado polvo", preguntas: "colágeno hidrolizado en polvo para qué sirve", openFoodFacts: "hydrolyzed collagen" },
    tituloFicha: "Composición y uso",
    ficha: [F("Presentación", "Polvo"), F("Ingrediente principal", "Colágeno hidrolizado"), F("Contenido neto", COMPLETAR, "g"), F("Registro sanitario")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Colágeno hidrolizado en polvo",
      categoria: "salud-y-bienestar",
      problema: "Quieres cuidar tu piel y tus articulaciones, pero las pastillas grandes te cansan y los batidos te dan pereza.",
      publico: "Adultos que cuidan su bienestar y quieren un suplemento fácil de tomar todos los días.",
      beneficios: [
        "Se disuelve rápido en agua, jugo o batido",
        "Un solo paso al día, sin pastillas",
        "Sin sabor fuerte: se combina con lo que ya tomas",
        "Viene en polvo, fácil de guardar y de llevar",
      ],
      precio: { valor: 69900, moneda: "COP" },
      objeciones: [
        "¿Cómo se toma?",
        "¿Tiene sabor?",
        "¿Cuánto tiempo dura un envase?",
        "¿Tiene registro sanitario?",
        "¿Qué pasa si no me gusta?",
      ],
      nivelConciencia: "problema",
      incluye: ["Envase de colágeno hidrolizado en polvo"],
      garantia: { dias: 30, condiciones: "Si no te convence, te devolvemos tu dinero dentro de los 30 días." },
      coloresMarca: ["#c2410c", "#fff7ed"],
      intensidad: 2,
    }),
  },
  {
    numero: 6,
    slug: "serum-vitamina-c-vitrina",
    tematica: "producto",
    tecnicas: TECNICAS,
    numeroSemilla: 733,
    bancos: ["p-belleza", "p-bienestar"],
    claves: ["serum", "piel", "vitamina", "gotero", "cosmetico", "skincare", "vitamin", "orange", "cosmetic", "bottle", "dropper"],
    fuentes: ["open-beauty-facts", "serpapi"],
    consultas: { shopping: "sérum vitamina c rostro", preguntas: "sérum de vitamina c cómo se usa", openBeautyFacts: "vitamin c serum" },
    tituloFicha: "Composición y uso",
    ficha: [F("Tipo", "Sérum facial"), F("Activo principal", "Vitamina C"), F("Contenido neto", COMPLETAR, "ml"), F("Ingredientes (INCI)")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Sérum facial de vitamina C",
      categoria: "belleza",
      problema: "Tu piel se ve apagada y cansada, y tu rutina de la mañana tiene demasiados pasos.",
      publico: "Mujeres y hombres que quieren una rutina de piel sencilla y constante.",
      beneficios: [
        "Textura ligera que se absorbe sin dejar la piel pegajosa",
        "Un paso fácil para sumar a tu rutina de la mañana",
        "Cuida el aspecto de tu piel día tras día",
        "Sirve con o sin maquillaje encima",
      ],
      precio: { valor: 54900, moneda: "COP" },
      objeciones: [
        "¿Sirve para piel sensible?",
        "¿Se puede usar de día?",
        "¿En cuánto tiempo se nota?",
        "¿Cuánto dura el frasco?",
        "¿Qué pasa si no me gusta?",
      ],
      nivelConciencia: "problema",
      incluye: ["Frasco de sérum de vitamina C"],
      garantia: { dias: 30, condiciones: "Si no te convence, te devolvemos tu dinero dentro de los 30 días." },
      coloresMarca: ["#ea580c", "#fffbeb"],
      intensidad: 2,
    }),
  },
  {
    numero: 7,
    slug: "cepillo-dental-electrico-vitrina",
    tematica: "producto",
    tecnicas: TECNICAS,
    numeroSemilla: 289,
    bancos: ["p-bienestar", "p-hogar"],
    claves: ["cepillo", "dientes", "dental", "bano", "sonrisa", "toothbrush", "teeth", "dental", "bathroom", "smile"],
    fuentes: ["serpapi", "wikimedia"],
    consultas: { shopping: "cepillo dental eléctrico recargable", preguntas: "cepillo dental eléctrico vale la pena" },
    tituloFicha: "Ficha técnica",
    ficha: [F("Tipo", "Cepillo dental eléctrico"), F("Alimentación", "Recargable"), F("Duración de la batería")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Cepillo dental eléctrico",
      categoria: "salud-y-bienestar",
      problema: "Te cepillas a las carreras y sientes que el cepillo manual no llega a todos lados.",
      publico: "Adultos y jóvenes que quieren un cepillado más cómodo sin gastar en un cepillo de marca cara.",
      beneficios: [
        "Cepillado más cómodo con movimiento automático",
        "Cabezal de repuesto fácil de cambiar",
        "Se carga y se guarda en el baño sin estorbar",
        "Un hábito más simple para toda la familia",
      ],
      precio: { valor: 79900, moneda: "COP" },
      objeciones: [
        "¿Sirve para encías sensibles?",
        "¿Cada cuánto se cambia el cabezal?",
        "¿Cuánto dura la carga?",
        "¿Se puede usar en niños?",
        "¿Qué pasa si llega dañado?",
      ],
      nivelConciencia: "solucion",
      incluye: ["Cepillo eléctrico", "Cabezal", "Cable de carga"],
      garantia: { dias: 30, condiciones: "Si llega con un defecto de fábrica, lo cambiamos sin costo." },
      coloresMarca: ["#0891b2", "#f0fdfa"],
      intensidad: 2,
    }),
  },
  {
    numero: 8,
    slug: "timbre-inteligente-vitrina",
    tematica: "producto",
    tecnicas: TECNICAS,
    numeroSemilla: 846,
    bancos: ["p-tecnologia", "p-hogar"],
    claves: ["timbre", "puerta", "camara", "seguridad", "casa", "doorbell", "door", "camera", "security", "home", "smart"],
    fuentes: ["serpapi", "wikimedia"],
    consultas: { shopping: "timbre inteligente con cámara wifi", preguntas: "timbre inteligente con cámara cómo funciona" },
    tituloFicha: "Ficha técnica",
    ficha: [F("Tipo", "Timbre inteligente con cámara"), F("Conexión"), F("Resolución de video")],
    textoCta: "Pídelo y paga al recibir",
    brief: brief({
      nombre: "Timbre inteligente con cámara",
      categoria: "tecnologia",
      problema: "Suena el timbre y no sabes quién es, o llegan paquetes y no estás para recibirlos.",
      publico: "Familias y personas que viven en casa o apartamento y quieren saber quién llega sin abrir la puerta.",
      beneficios: [
        "Ves quién toca desde tu celular",
        "Te avisa cuando alguien llega, aunque no estés",
        "Habla con quien llega sin abrir la puerta",
        "Se instala en la puerta sin obras grandes",
      ],
      precio: { valor: 149900, moneda: "COP" },
      objeciones: [
        "¿Necesita internet?",
        "¿Es difícil de instalar?",
        "¿Se ve de noche?",
        "¿Funciona con la aplicación de mi celular?",
        "¿Qué pasa si llega dañado?",
      ],
      nivelConciencia: "solucion",
      incluye: ["Timbre con cámara", "Piezas de instalación", "Manual en español"],
      garantia: { dias: 30, condiciones: "Si llega con un defecto de fábrica, lo cambiamos sin costo." },
      coloresMarca: ["#2563eb", "#f8fafc"],
      intensidad: 2,
    }),
  },
];

export const ESPACIALES = VITRINA.filter((e) => e.tematica === "espacio");
export const entradaPorSlug = (slug: string): EntradaVitrina | undefined => VITRINA.find((e) => e.slug === slug);
